apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out"]
    volumeMounts:
    - name: data-volume
      mountPath: /opt # Mount the volume at /opt in the container
  volumes:
  - name: number-volume
    hostPath:
      path: /data # Path on the host machine where the volume will be created
      type: DirectoryOrCreate

