apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Specify the size of the volume to claim
  volumeMode: Filesystem







# kubectl create -f 02-2-persistent-volume-claim-definition.yaml
# kubectl get persistentvolumeclaims
# kubectl get pvc
# kubectl describe pvc myclaim
# kubectl delete pvc myclaim
# kubectl delete pv pv-voll # If you want to delete the associated PV as well
# kubectl get pv
# kubectl get persistentvolumes
# kubectl describe pv pv-voll
# kubectl delete pv pv-voll # If you want to delete the PV after deleting the