apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany, ReadWriteMany, ReadWriteOnce
  capacity:
    storage: 1Gi # 1Gi, 10Gi, etc.
  hostPath:
    path: /tmp/data # not used in production, use NFS or other storage solutions
    
  # awsElasticBlockStore:
  #   volumeID: aws://us-west-2a/vol-12345678
  #   fsType: ext4
  # gcePersistentDisk:
  #   pdName: my-pd
  #   fsType: ext4
  # azureDisk:
  #   diskName: my-disk
  #   diskURI: /subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myDisk




# kubectl apply -f 02-persistent-volumes-definition.yaml
# kubectl get persistentvolumes
# kubectl get pv
# kubectl describe pv pv-voll
# kubectl delete pv pv-voll
