apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassname: google-storage # Specify the storage class to use
  resources:
    requests:
      storage: 500Mi