apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flight.com
spec:
  scope: Namespaced # Indicates that the resource is namespaced
  group: flight.com #  Custom resource group mentioned in the FlightTicket API in the flightticket.yaml
  names:
    kind: FlightTicket # mentioned in flightticket.yaml in the kind field
    singular: flightticket # singular name for the resource
    plural: flighttickets # plural name for the resource
    shortNames: [ft] # short name for the resource
  versions:
  - name: v1 # version of the custom resource
    served: true
    storage: true
    schema:
      opemAPISchema:
        type: object
        properties:
          from:
            type: string
            description: "Departure city"
          to:
            type: string
            description: "Destination city"
          number:
            type: integer
            description: "Number of tickets"
            minimum: 1
            maximum: 10



# kubectl create -f flightticket-custom-definition.yaml
# kubectl get crd flighttickets.flight.com
# kubectl describe crd flighttickets.flight.com
# kubectl delete crd flighttickets.flight.com



# then create the custom resource instance
# kubectl apply -f flightticket.yaml
# kubectl get flighttickets
# kubectl describe flightticket my-flight-ticket
# kubectl delete flightticket my-flight-ticket
