apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubernetes resources to be managed by kustomize
resources:
  - nginx-depl.yaml
  - nginx-service.yaml

# Customizations that need to be made
labels:
  - includeSelectors: true
    pairs:
      company: IT-Consulting, Mojtaba-Ghanaat-Pisheh



# sample commands
# Navigate to the demos directory
# cd c:\me\git\Kubernetes-practices\demos\
# Run kustomize build on the 09-kustomize folder
# kustomize build 09-kustomize/
# Navigate to the kustomize directory
# cd c:\me\git\Kubernetes-practices\demos\09-kustomize\
# Run kustomize build on current directory
# kustomize build .

# to apply the build

# kustomize build . | kubectl  apply -f -
# service/nginx-loadbalancer-service created 
# deployment.apps/nginx-deployment created service/nginx-loadbalancer-service created


# or

# kubectl apply -k .
# service/nginx-loadbalancer-service created
# deployment.apps/nginx-deployment created

# delete resources

# kustomize build . | kubectl delete -f -
# service "nginx-loadbalancer-service" deleted
# deployment.apps "nginx-deployment" deleted

# or

# kubectl delete -k .
# service "nginx-loadbalancer-service" deleted
# deployment.apps "nginx-deployment" deleted