apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: image-name
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      initialDelaySeconds: 5 #  Delay before the first probe to warm up the application
      failureThreshold: 8 # Number of consecutive failures before marking the pod as not ready
      periodSeconds: 10 #  Interval between readiness probes
      timeoutSeconds: 2 #  Timeout for each probe

    #  readinessProbe:
    #    tcpSocket:
    #      port: 3306
    
    #  readinessProbe:
    #    excec:
    #      command:
    #      - /bin/sh
    #      - -c
    #      - echo "Ready"

    