apiVersion: v1
kind: pod
metadata:
  name: api-pod
spec:
  containers:
  - name: my-api-container
    image: my-api-container

---

apiVersion: v1
kind: pod
metadata:
  name: db-pod
  labels:
    role: db # Ensure the pod has the label that matches the network policy
spec:
  containers:
  - name: my-db-container
    image: my-db-container
