apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-store-pvc
spec:
  volumeName: story-host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
