apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80


# kubectl create -f 01-pod-definition.yaml
# kubectl get pods
# kubectl describe pod myapp-pod
# kubectl delete pod myapp-pod
# kubectl delete pods -l app=myapp
# kubectl delete pods -l type=frontend
# kubectl delete pods -l app=myapp,type=frontend
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true --all-namespaces
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true --all-namespaces=false
