apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota  # Name of the ResourceQuota
spec:
  hard:
    requests.cpu: "2"  # Maximum CPU requests across all pods
    requests.memory: "5Gi"  # Maximum memory requests across all pods
    limits.cpu: "10"  # Maximum CPU limits across all pods
    limits.memory: "10Gi"  # Maximum memory limits across all pods
    pods: "100"  # Maximum number of pods in the namespace
    services: "10"  # Maximum number of services in the namespace