apiVersion: v1
kind: Secret
metadata:
  name: app-secret  # Name of the secret
data:
  DB_USERNAME: "admin"
  DB_PASSWORD: "some-password"  # Base64 encoded value of 'secret123'
  ssh-privatekey: "some-key"  # Base64 encoded value of 'ssh-key.pem'
  ssh-public: "some-key"  # Base64 encoded value of 'ssh-key.pub'




# Imperative Secret Definition
# kubectl create secret generic app-secret \
#  --from-literal=username=admin \
#  --from-literal=password=secret123 \
#  --from-file=ssh-privatekey=ssh-key.pem \
#  --from-file=ssh-publickey=ssh-key.pub

#
# kubectl create secret generic app-secret \
# --from-file=ssh-private
# --from-file=ssh-publickey=ssh-key.pub
# --from-file=ssh-privatekey=ssh-key.pem


# kubectl get secrets
# kubectl get secret app-secret
# kubectl describe secret app-secret
# kubectl delete secret app-secret
# kubectl delete secret app-secret --cascade=foreground
# kubectl delete secret app-secret --cascade=background
# kubectl delete secret app-secret --cascade=orphan
# kubectl delete secret app-secret --cascade=foreground --wait=true
# kubectl delete secret app-secret --cascade=background --wait=true
# kubectl delete secret app-secret --cascade=orphan --wait=true
# kubectl delete secret app-secret --cascade=foreground --wait=false
# kubectl delete secret app-secret --cascade=background --wait=false
# kubectl delete secret app-secret --cascade=orphan --wait=false
# kubectl delete secret app-secret --cascade=foreground --now=true
# kubectl delete secret app-secret --cascade=background --now=true
# kubectl delete secret app-secret --cascade=orphan --now=true


