# SecurityContext in pod level
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  securityContext:
    runAsUser: 1000  # Run the container as user ID 1000
    runAsGroup: 3000  # Run the container as group ID 3000
    fsGroup: 2000  # Set the filesystem group ID to 2000
    # capabilities are only supported in container level
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "3600"]

---


# SecurityContext in Container level
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000  # Run the container as user ID 1000
        runAsGroup: 3000  # Run the container as group ID 3000
        # capabilities are only supported in container level
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]  # Add capabilities to the container