apiVersion: v1
kind: Secret
# Since 1.22 this type of secret is no longer used to mount service account tokens automatically.
# You can use kubectl create token <service-account-name> to create a token for a ServiceAccount.
type: kubernetes.io/service-account-token #  This type indicates that this secret is a ServiceAccount token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: dashboard-sa  # Name of the ServiceAccount

