apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-account
  namespace: default  # Change this if you want to use a different namespace


---

apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard  # Name of the pod
spec:
  serviceAccountName: demo-service-account  # Service account to use for this pod
  containers:
    - name: kubernetes-dashboard  # Name of the container
      image: kubernetesui/dashboard:v2.5.1  # Docker image for the Kubernetes Dashboard
      ports:
        - containerPort: 9090  # Port exposed by the container
  # automountServiceAccountToken: false # prevent automatically mount the service account token

---



# Sample usage:
# To create this ServiceAccount, run:
#   kubectl apply -f 12-service-account-definition.yaml
#
# To use this ServiceAccount in a Pod, add the following to your Pod spec:
#
#   serviceAccountName: demo-service-account


#   kubectl get serviceaccounts
#   kubectl get sa
#   kubectl get serviceaccount demo-service-account
#   kubectl describe serviceaccount demo-service-account
#   kubectl describe sa demo-service-account
#   kubectl get pods --all-namespaces -o wide

# kubectl exec -it my-kubernetes-dashboard ls /var/run/secrets/kubernetes.io/serviceaccount
# kubectl exec -it my-kubernetes-dashboard cat /var/run/secrets/kubernetes.io/serviceaccount/token


# imperative commands to create a ServiceAccount:
#   kubectl create serviceaccount demo-service-account
#   kubectl create sa demo-service-account
#   kubectl create serviceaccount demo-service-account --namespace=default
#   kubectl create sa demo-service-account --namespace=default
#   kubectl create serviceaccount demo-service-account --dry-run=client -o yaml > 12-service-account-definition.yaml
#   kubectl create sa demo-service-account --dry-run=client -o yaml > 12-service-account-definition.yaml

# v1.24  - tokens are no longer automatically created for ServiceAccounts
# v1.24  - automountServiceAccountToken: false is the default behavior
# v1.24  - to create a token for a ServiceAccount, use the following command:
#   kubectl create token demo-service-account --duration=24h
#   kubectl create token demo-service-account --duration=24h --namespace=default

