apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 8080
    # define tolerations for the pod
    # This allows the pod to be scheduled on nodes with specific taintstolerations:
  
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule" 
      # "NoSchedule" means the pod will not be scheduled on nodes with this taint
      # "PreferNoSchedule" means the pod will be scheduled on nodes with this taint if possible
      # "NoExecute" means the pod will be evicted from nodes with this taint
    



# kubectl describe node kubemaster
# kubectl taint nodes kubemaster key=value:NoSchedule
# kubectl taint nodes kubemaster key=value:PreferNoSchedule
# kubectl taint nodes kubemaster key=value:NoExecute

# to remove a taint from a node, use the following command: the - sign at the end of the taint key-value pair
# kubectl taint node controlplane node-role.kubernetes.io/control-plane:NoSchedule-
# result: node/controlplane untainted

# kubectl taint nodes node01 spray=mortein:NoSchedule

# kubectl create -f 14-taint-toleration.yaml

