apiVersion: v1
kind: Pod
metadata:
  name: colocated-containers-demo
spec:
  containers:
    - name: main-app
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "echo Hello from sidecar > /shared-data/index.html && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared-data
  volumes:
    - name: shared-data
      emptyDir: {}