apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80


# Create the pod from this manifest file
# kubectl create -f 01-pod-definition.yaml

# List all pods in the current namespace
# kubectl get pods

# Show detailed pod info (events/status/IP)
# kubectl describe pod myapp-pod

# Get pod output in YAML format
# kubectl get pod myapp-pod -o yaml

# Get pod output in JSON format
# kubectl get pod myapp-pod -o json

# Get pod IP address
# kubectl get pod myapp-pod -o wide

# Stream pod logs
# kubectl logs myapp-pod

# Stream logs and follow (tail -f)
# kubectl logs myapp-pod -f

# Show previous container logs (useful after crash)
# kubectl logs myapp-pod --previous

# Exec into the pod (interactive shell)
# kubectl exec -it myapp-pod -- /bin/bash

# Run a single command inside the pod
# kubectl exec myapp-pod -- ls /usr/share/nginx/html

# Port-forward pod port 80 to localhost:8080
# kubectl port-forward myapp-pod 8080:80

# Edit pod live (opens in editor)
# kubectl edit pod myapp-pod

# Patch a pod label
# kubectl label pod myapp-pod env=dev

# Overwrite an existing label
# kubectl label pod myapp-pod type=backend --overwrite

# Annotate a pod
# kubectl annotate pod myapp-pod description="my frontend pod"

# Get pod status phase only
# kubectl get pod myapp-pod -o jsonpath='{.status.phase}'

# Watch pod status changes in real time
# kubectl get pod myapp-pod --watch

# Copy a file from pod to local machine
# kubectl cp myapp-pod:/usr/share/nginx/html/index.html ./index.html

# Copy a local file into the pod
# kubectl cp ./index.html myapp-pod:/usr/share/nginx/html/index.html

# Delete a single pod by name
# kubectl delete pod myapp-pod

# Delete pods matching label app=myapp
# kubectl delete pods -l app=myapp

# Delete pods matching label type=frontend
# kubectl delete pods -l type=frontend

# Delete pods matching app=myapp AND type=frontend
# kubectl delete pods -l app=myapp,type=frontend

# Force delete matching pods immediately (no grace period)
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force

# Force delete immediately and do not wait for completion
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false

# Force delete with a 10s client timeout
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s

# Same as above but ignore if pods already removed
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found

# Same as above, explicit boolean for ignore-not-found
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true

# Force delete across all namespaces
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true --all-namespaces

# Explicitly target current namespace only
# kubectl delete pods -l app=myapp,type=frontend --grace-period=0 --force --wait=false --timeout=10s --ignore-not-found=true --all-namespaces=false
