# DEPRECATED: ReplicationController is deprecated and replaced by ReplicaSet.
# ReplicaSet supports set-based label selectors (matchExpressions) in addition
# to equality-based ones, making it more flexible.
# In practice, you should use a Deployment (which manages ReplicaSets automatically)
# rather than using either ReplicationController or ReplicaSet directly.

apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80

# kubectl create -f 02-rc-controller.yaml
# kubectl get replicationcontrollers
# kubectl get pods
# kubectl describe replicationcontroller myapp-rc
# kubectl delete replicationcontroller myapp-rc
# kubectl delete pods -l app=myapp
# kubectl delete pods -l type=frontend