# Pod using all environment variables from Secret
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color-container
      image: mojtabaghp/kub-demo-simple-webapp-color:latest
      ports:
        - containerPort: 8080
      # Import all key-value pairs from ConfigMap as environment variables
      envFrom:
        - secretRef:
            name: app-secret

---
# Pod using a single environment variable from Secret
# Pod using all environment variables from Secret
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color2
spec:
  containers:
    - name: simple-webapp-color-container
      image: mojtabaghp/kub-demo-simple-webapp-color:latest
      ports:
        - containerPort: 8080
      # Import all key-value pairs from ConfigMap as environment variables
      env:
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
              