# =============================================================================
# Pods consuming a Secret — 3 injection methods
# =============================================================================
# Requires: Secret "app-secret" from 09-secret-definition.yaml
#
# Works exactly like ConfigMap injection, but for sensitive data.
# Secrets are base64-encoded (NOT encrypted) by default.
#
# Method 1 — envFrom:      Inject ALL keys as env vars (bulk)
# Method 2 — env/valueFrom: Inject a SINGLE key as a named env var (selective)
# Method 3 — volume:        Mount keys as files inside the container
#
# Note: Env vars from Secrets are decoded automatically — your app receives
# the plain-text value, not the base64-encoded string.
# =============================================================================


# -----------------------------------------------------------------------------
# Method 1: envFrom — inject ALL Secret keys as environment variables
# -----------------------------------------------------------------------------
# Every key in the Secret becomes an env var with the same name.
# e.g. DB_USERNAME=admin, DB_PASSWORD=secret123, etc.

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color-container
      image: mojtabaghp/kub-demo-simple-webapp-color:latest
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret       # Must match the Secret metadata.name

---

# -----------------------------------------------------------------------------
# Method 2: env/valueFrom — inject a SINGLE key as an environment variable
# -----------------------------------------------------------------------------
# Only the specified key is injected. You control the env var name.
# Useful when the Pod only needs one credential (e.g., a DB password).

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-single-env
spec:
  containers:
    - name: simple-webapp-color-container
      image: mojtabaghp/kub-demo-simple-webapp-color:latest
      ports:
        - containerPort: 8080
      env:
        - name: DB_PASSWORD        # Env var name inside the container
          valueFrom:
            secretKeyRef:
              name: app-secret     # Secret name
              key: DB_PASSWORD     # Key to read from the Secret

---

# -----------------------------------------------------------------------------
# Method 3: volume — mount Secret keys as files
# -----------------------------------------------------------------------------
# Each key becomes a file (filename = key, content = decoded value).
# Files are mounted with permissions 0644 by default (use defaultMode to change).
# Updates to the Secret are eventually reflected without pod restart.

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-volume
spec:
  containers:
    - name: simple-webapp-color-container
      image: mojtabaghp/kub-demo-simple-webapp-color:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets   # Files: /etc/secrets/DB_USERNAME, DB_PASSWORD, etc.
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret     # Secret to mount
        defaultMode: 0400          # Restrict file permissions (owner read-only)