# =============================================================================
# Kubernetes Secret — Educational Reference
# =============================================================================
#
# A Secret stores sensitive data such as passwords, tokens, and SSH keys.
# Similar to ConfigMaps, but intended for confidential information.
#
# Key facts:
#   - Values under "data:" must be base64-encoded.
#   - Use "stringData:" to provide plain-text values (K8s encodes them for you).
#   - Secrets are namespace-scoped (same namespace as the consuming Pod).
#   - Max size per Secret: 1 MiB.
#   - Secrets are NOT encrypted by default — they are only base64-encoded.
#     Enable Encryption at Rest for real protection (see 10-encryption-at-rest).
#
# Secret types:
#   - Opaque              → Generic key-value (default, used here)
#   - kubernetes.io/tls   → TLS cert + key
#   - kubernetes.io/dockerconfigjson → Docker registry credentials
#   - kubernetes.io/ssh-auth         → SSH private key
#
# See 09-pod-secret-definition.yaml for Pods that consume this Secret.
# =============================================================================


# -----------------------------------------------------------------------------
# Secret definition using "data" (base64-encoded values)
# -----------------------------------------------------------------------------
# To encode: echo -n 'admin' | base64        → YWRtaW4=
# To decode: echo 'YWRtaW4=' | base64 -d     → admin

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque                   # Default type for generic key-value secrets
data:
  DB_USERNAME: YWRtaW4=        # base64 of 'admin'
  DB_PASSWORD: c2VjcmV0MTIz    # base64 of 'secret123'
  ssh-privatekey: c29tZS1rZXk=  # base64 of SSH private key content
  ssh-publickey: c29tZS1rZXk=   # base64 of SSH public key content

---

# -----------------------------------------------------------------------------
# Secret definition using "stringData" (plain text — K8s encodes for you)
# -----------------------------------------------------------------------------
# Easier to read/write. K8s converts to base64 when stored.

apiVersion: v1
kind: Secret
metadata:
  name: app-secret-plain
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: secret123


# =============================================================================
# Imperative Commands — Create Secrets
# =============================================================================

# Create from literal key-value pairs
# kubectl create secret generic app-secret \
#   --from-literal=DB_USERNAME=admin \
#   --from-literal=DB_PASSWORD=secret123

# Create from files (filename becomes the key)
# kubectl create secret generic app-secret \
#   --from-file=ssh-privatekey=ssh-key.pem \
#   --from-file=ssh-publickey=ssh-key.pub

# Create a TLS secret from cert and key files
# kubectl create secret tls tls-secret \
#   --cert=tls.crt --key=tls.key

# Create a Docker registry secret
# kubectl create secret docker-registry regcred \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=user \
#   --docker-password=pass

# Generate YAML without creating (dry-run)
# kubectl create secret generic app-secret \
#   --from-literal=DB_PASSWORD=secret123 \
#   --dry-run=client -o yaml > secret.yaml

# =============================================================================
# Declarative Commands — Apply
# =============================================================================

# Apply this Secret definition
# kubectl apply -f 09-secret-definition.yaml

# Apply the Pod that consumes this Secret
# kubectl apply -f 09-pod-secret-definition.yaml

# =============================================================================
# Inspect Secrets
# =============================================================================

# List all secrets in the current namespace
# kubectl get secrets

# Describe a secret (shows keys but NOT values)
# kubectl describe secret app-secret

# Get secret in YAML (values shown as base64)
# kubectl get secret app-secret -o yaml

# Decode a specific key's value
# kubectl get secret app-secret -o jsonpath='{.data.DB_PASSWORD}' | base64 -d

# Verify env vars inside a running pod
# kubectl exec simple-webapp-color -- env | grep DB_

# =============================================================================
# Edit / Update Secrets
# =============================================================================

# Edit a secret live (opens in editor, values shown as base64)
# kubectl edit secret app-secret

# Replace a secret from file
# kubectl replace -f 09-secret-definition.yaml

# =============================================================================
# Delete Secrets
# =============================================================================

# Delete by name
# kubectl delete secret app-secret

# Delete from file
# kubectl delete -f 09-secret-definition.yaml
