apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp  # Label to identify the pod
    type: frontend  # Additional label to categorize the pod
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
    - containerPort: 8080 

    # kubectl get pods --selector app=myapp
    # kubectl get pods --selector type=frontend
    # kubectl get pods --selector bu=finance | --no-headers wc -l
    # kubectl get all --selector env=prod --no-headers
    # kubectl get pods --selector env=prod,bu=finance,tier=frontend

    # kubectl get pods -l app=myapp
    # kubectl get pods -l type=frontend
    # kubectl get pods -l app=myapp,type=frontend
    # kubectl get pods -l app=myapp -l type=frontend
    # kubectl get pods -l app=myapp,type=frontend --show-labels
    # kubectl get pods -l app=myapp,type=frontend -o wide

