apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
    app: App1 #  Label to identify the replicaset
    type: frontend
  annotations: #  Additional metadata for the replicaset
    description: "This is a simple web application replicaset"
    buildVersion: 1.0.0 # Annotations for additional metadata
spec:
  replicas: 3
  selector:
    matchLabels: # Match pods with these labels
      app: App1
  template:
    metadata:
      labels:
        app: App1 # Label to identify the pod
        type: frontend
    spec:
      containers:
      - name: simple-webapp
        image: simple-webapp:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: App1 # Selector to match pods with the label 'app: App1'
  ports:
  - port: 80
    targetPort: 9376
