apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200)"]
      restartPolicy: Never
  backoffLimit: 4 # Number of retries before marking the job as failed
    

# ---
# Sample commands:
# kubectl apply -f 06-job-pod-definition.yaml
# kubectl get jobs
# kubectl get pods --show-labels
# kubectl logs <job-pod-name>
# kubectl delete -f 06-job-pod-definition.yaml
