apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-policy.webhook.com
webhooks:
- name: pod-policy.webhook.com
  clientConfig:
    # url: "https://external-server.example.com/webhook"
    service:
      name: webhook-service
      namespace: "webhook-namespace"
    caBundle: "CA_CERTIFICATE_BASE64_ENCODED"
  rules:
  - apiGroups: [""]
    operations: ["CREATE", "UPDATE"]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"



    # kubectl apply -f  04-validating-webhook-configuration.yaml
    # kubectl get validatingwebhookconfigurations
    # kubectl describe validatingwebhookconfiguration pod-policy.webhook.com
    # kubectl delete validatingwebhookconfiguration pod-policy.webhook.com
    
